### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by patzm** [yktoo/indicator-sound-switcher#103]
hi @yktoo,
I really like this package. Sadly, it got removed from the AUR some time ago. Today I found the time and took the liberty of writing and releasing a package for it. I hope this is fine by you.
If yes, should I file a PR to add it to the installation instructions of this repo?

**Comment by patzm** [comment]
I got some cool feedback in [this reddit post](https://www.reddit.com/r/archlinux/comments/kr8n3a/indicatorsoundswitcher_is_back_in_the_aur_and_my/gi8am09?utm_source=share&utm_medium=web2x&context=3). I incorporated that. TLDR: the new package name on the AUR is now `indicator-sound-switcher` (without the `-git` suffix).
Link: https://aur.archlinux.org/packages/indicator-sound-switcher/
The AUR has an awesome WIKI. In essence, the key instructions are [here](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Publishing_new_package_content). But in short, you would have to do the following:
1. enable authentication [link](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Authentication):
   1. create an account in the AUR
   1. upload you public ssh key to your account
1. run
    ```bash
    git clone ssh://aur@aur.archlinux.org/indicator-sound-switcher.git
    cd indicator-sound-switcher
    # change PKGBUILD, probably just updating the version tag and md5 sum
    makepkg --printsrcinfo > .SRCINFO
    git add PKGBUILD .SRCINFO
    git commit -m "useful commit message"
    git push
    ```

I am not sure if I have to add you as a maintainer. I think you can simply push to that repo and that itself is a release. If that is the case, just ping me :wink:.

**Comment by yktoo** [comment]
Thanks, that's handy, we'll check how it'll fly next time.

As I'm not familiar with AUR/Arch, could you please provide some instructions for the Installation document so I can amend it on my website?

**Comment by patzm** [comment]
Sure. I would add something like the following. I will write it in valid markdown right away, so I suggest you _edit_ my comment to copy the literal version of it.

## Arch
This installation method assumes that any [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers) is already installed, specifically any of the [pacman wrappers](https://wiki.archlinux.org/index.php/AUR_helpers#Pacman_wrappers). For instance, if you are using [`yay`](https://github.com/Jguer/yay), simply run:
```bash
yay -S indicator-sound-switcher
```
If you don't want to use any helper, refer to [this article](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages) on how to manually build and install packages from AUR. Download the `PKGBUILD` from [here](https://aur.archlinux.org/packages/indicator-sound-switcher) (right hand side, e.g. _View PKGBUILD_ or _Download snapshot_).

**Comment by yktoo** [comment]
Thanks @patzm, the info is incorporated into the [SSI web page](https://yktoo.com/en/software/sound-switcher-indicator/#installation).
