### ISSUE TITLE
Preferences: display device information in the list

### ISSUE THREAD

**Issue by felagund** [yktoo/indicator-sound-switcher#105]
I use two monitors with my laptop that I both connect wia USB-C to my laptop, not necessarily caring which port I use for which. Only one monitor has speakers I would like to use. They both appear as active in the preferences. It would be great if they were distinguishable by "device.product.name" property lists under ports with pacpl.

**Comment by yktoo** [comment]
Makes sense, I believe I could also add the vendor name.
