### ISSUE TITLE
[Request] single global shortcut for toggling between the output/input devices?

### ISSUE THREAD

**Issue by shakakibara12** [yktoo/indicator-sound-switcher#106]
Can we add a single global shortcut for toggling between the output/input devices? Thanks
sorry wrong label! :cry:

**Comment by yktoo** [comment]
What do you mean exactly with "toggling between the output/input devices"?

**Comment by shakakibara12** [comment]
> What do you mean exactly by "toggling between the output/input devices"?

Alright imma explain...
So i have 2 output devices, headphone and speaker. I have set a keyboard shortcut for my speaker, when i press it then the audio comes from the speaker, now to switch back my output to my headphone i have to press a different keybinding or use my mouse. What i want is to have a single keyboard shortcut, so when i press it, it switches playback to speaker and if i press it again then the playback changes to headphone. I tried giving same keybinding to both the output devices but it won't work meaning only one keybinding can be given to one device/port. 
**Thank you for replying**
