### ISSUE TITLE
JBL Quantum 800 mic - keeps switching back to Built-in Audio Internal Microphone

### ISSUE THREAD

**Issue by calen-legaspi** [yktoo/indicator-sound-switcher#109]
Indicator-sound-switcher can see my JBL Quantum 800 mic, and I can select the radio button, but after some time it switches back to Built-in Audio Internal Microphone. 

Steps to Reproduce:

1. Select to JBL Quantum 800 mic
2. Record self using Sound Recorder
3. Play back recording, note that playback is noisy, indicating that built-in mic was being used and not the JBL Quantum 800 (noise canceling) mic
4. Check indicator-sound-switcher again, note that the mic setting is back to Built-in Audio Internal Microphone

![Screenshot from 2021-06-23 21-36-49](https://user-images.githubusercontent.com/806824/123106771-830a1f80-d46b-11eb-80c6-8d2fe61d3595.png)

**Comment by yktoo** [comment]
What happens after the step 1, does the item for the JBL card get selected? What happens in another switcher app, for instance `pavucontrol`, does it follow the changes initiated in the SSI, and vice versa?

**Comment by yktoo** [comment]
Please reopen if the issue persists.
