### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Frost4142** [yktoo/indicator-sound-switcher#112]
Нет иконки в системном трее

 - OS Ubuntu Studio
 - kernel 5.11.0-41-lowlatency
 - XFCE
 - Sound Switcher Indicator version  2.3.6
 - 
 Sound Switcher Indicator  установлен через репозиторий 
Программа работает. Нет только иконки в трее. Точнее пустое место там где должна быть иконка. Темы иконок менял без результата. Может надо куда-то положить svg что бы программа их увидела ?

**Comment by yktoo** [comment]
Дубликат #91, пожалуйста, добавьте информацию к тому багрепорту. Мне воспроизвести эту ошибку не удалось.
