### ISSUE TITLE
Slow refresh of menu

### ISSUE THREAD

**Issue by finsterwalder** [yktoo/indicator-sound-switcher#114]
First of all: Thanks a lot for this wonderful tool! Have been looking for something like this for quite a while!
I configured hotkeys to switch my output sources, which works great.
But when I execute a hotkey, the menu still shows the old source, even though the system already shows the new output and uses it.
When I switch the source via system preferences, the menu is updated immediately. So this only happens when switching via Hotkey.

**Comment by yktoo** [comment]
Does the problem persist if you restart the indicator? Can you attach the console log (run the indicator with `indicator-sound-switcher -vv`)?

**Comment by finsterwalder** [comment]
When restarting the app, the correct output is marked. But using a hotkey to change the output still does not change the selection.

I did execute this szenario with -vv and attached the output here:
[indicator-sound-switcher.log](https://github.com/yktoo/indicator-sound-switcher/files/7821296/indicator-sound-switcher.log)
.

**Comment by yktoo** [comment]
I don't see anything fishy in the log so tend to think it's a bug in your DE.

What are your distro and DE?

**Comment by finsterwalder** [comment]
What do you mean by DE?
I use plain Ubuntu 20.04.3 LTS with GNOME 3.36.8.

**Comment by yktoo** [comment]
DE = desktop environment, Gnome in your case. Well, nothing too bizarre here as I see.

**Comment by yktoo** [comment]
Is it really slow or the change of selection doesn't happen *at all* when using a shortcut key?

**Comment by finsterwalder** [comment]
It doesn't happen at all actually.

**Comment by yktoo** [comment]
Could you check if this is still the case in the latest version?

**Comment by finsterwalder** [comment]
I haven't used hotkeys in a while. I also installed a new system in the meantime (Ubuntu 22.04.01 LTS, GNOME Shell 42.2).
Now hotkeys don't work at all. I tried to configure hotkeys Ctrl-Alt-1 and Ctrl-Alt-2. But nothing happens, when I hit those Hotkeys. In the log output nothing changes when I hit the hotkey. Seams like the hotkey doesn't even reach the application.

**Comment by yktoo** [comment]
@finsterwalder I think it's a wrong thread, you'd better comment in #125

**Comment by finsterwalder** [comment]
Yes shortcut binding seams to be broken on my system currently, so I can't currently test, whether this bug is gone or not.

**Comment by finsterwalder** [comment]
After fixing the shortcut-issue I see that the menu changes now. So this bug seams to be fixed.

**Comment by finsterwalder** [comment]
I have to take that back. After starting my computer from suspend today, the menu does not update again when switching sound output source via Hotkey...

**Comment by yktoo** [comment]
Is this issue still happening?

**Comment by finsterwalder** [comment]
I'm not using Linux anymore, so I can't tell. ;-)
