### ISSUE TITLE
Support for Native Instruments Audio 8 DJ

### ISSUE THREAD

**Issue by skelmy** [yktoo/indicator-sound-switcher#116]
Description:

With a Native Instruments Audio 8 DJ going to: Preferences>Audio 8 DJ> all the the options are greyed out, unlike any other outputs this says Out: None #dummy_out and In: None #dummy_out. 
All options to the right in Port settings are greyed out so you cannot then create any "Keyboard shortcut" for this at all or set any other options.
The Sound Indicator Switcher applet will allow only to switch from the Audio 8 DJ, but not back to it, however in all other audio settings apps you can switch backwards and forwards with no problems, so this is specific to Indicator Sound Switcher.

**Expected behavior**
Should allow for Port Settings and switching of dummy audio? Or is this specific to this or these Native Instruments Audio Interlace/s?

![Audio_8_Sound_Indicator_Switcher](https://user-images.githubusercontent.com/99342437/153224948-a1e53806-027d-4873-9553-042e12577716.png)

**Comment by yktoo** [comment]
Could you provide a console log (obtained by running `indicator-sound-switcher -vv` in a terminal)?

**Comment by yktoo** [comment]
Closing as stale
