### ISSUE TITLE
[BUG] build_package doesn't work on non dpkg systems

### ISSUE THREAD

**Issue by mxmilkiib** [yktoo/indicator-sound-switcher#123]
**Describe the bug**

```
 ./build_package 
Building indicator-sound-switcher version 2.3.9 revision 1...
./build_package: line 40: dpkg-parsechangelog: command not found
ERROR: The changelog doesn't start with the entry for version 2.3.9-1
```

I'm on Arch btw.

**Comment by yktoo** [comment]
I've originally made this script for myself to facilitate packaging, so this "works as designed."

If you just want to install from source, I'd recommend using the [`setup.py` script](https://yktoo.com/en/software/sound-switcher-indicator/#source-tarball).

**Comment by mxmilkiib** [comment]
I don't want to install, I just wanted to build the latest git version to test the black icon in a black icon tray problem. The AUR entry only points to the release, not head. But there was no obvious `indicator-sound-switcher` after build to run.

**Comment by yktoo** [comment]
Unfortunately I'm not familiar with Arch builds, so any help would be appreciated.
