### ISSUE TITLE
[Enhancement] Change Default 

### ISSUE THREAD

**Issue by roraigh** [yktoo/indicator-sound-switcher#124]
I was a little bummed not to find a set option as default.
trying to change the default audio in Linux is a pain in terminal and having a clean GUI option would be great!

**Comment by yktoo** [comment]
I feel pretty reluctant of adding the *default* option to the indicator.

* This is a GUI application, which starts with the user session and the meaning of which is providing the user with sound switching controls.
* Selecting the default source or sync should happen, on the contrary, when the PA daemon starts. Which PulseAudio has the official means for.

Does the [standard way of setting default sink](https://wiki.archlinux.org/title/PulseAudio/Examples#Set_the_default_output_sink) in `default.pa` not work for you?
