### ISSUE TITLE
[BUG] Keyboard shortcuts don't work in Wayland

### ISSUE THREAD

**Issue by OoDeLally** [yktoo/indicator-sound-switcher#125]
**Describe the bug**

On a fresh install of Ubuntu 22.04 LTS.

I've set shortcut to output device ports. They do not work. I've tested various keyboard combinations and none of them work.
When switching sound from the graphical menu, it works flawlessly.

I used to use Linux Mint before Ubuntu, and it was working fine. It stopped working on a fresh Ubuntu (vanilla) install.

To this day I do not know whether the issue is from the SoundSwitch, or Ubuntu which may not let the keystroke event go through.

**To Reproduce**
On Ubuntu 22.04 LTS, set some shortcuts, and strike them. It does nothing.

**Expected behavior**
Sound output should be switched.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Desktop environment Gnome 42.2
 - Sound Switcher Indicator version: 2.3.9
 - Installation source: PPA

**Indicator config:**
```json
{
    "devices": {
        "alsa_card.pci-0000_03_00.1": {
            "ports": {
                "hdmi-output-0": {
                    "visible": false
                },
                "hdmi-output-1": {},
                "hdmi-output-2": {},
                "hdmi-output-3": {},
                "hdmi-output-4": {},
                "hdmi-output-5": {
                    "visible": false
                }
            }
        },
        "alsa_card.usb-Microsoft_Microsoft___LifeCam_Cinema_TM_-02": {
            "ports": {
                "analog-input-mic": {
                    "visible": false
                }
            }
        },
        "alsa_card.pci-0000_00_1f.3": {
            "ports": {
                "analog-input-front-mic": {},
                "analog-input-rear-mic": {},
                "analog-input-linein": {},
                "analog-output-lineout": {},
                "analog-output-headphones": {
                    "shortcut": "<Primary>F8"
                },
                "iec958-stereo-output": {
                    "shortcut": "<Primary>F9"
                }
            }
        }
    },
    "show_inputs": false
}
```

**Indicator log:**
```
** (indicator-sound-switcher:9024): WARNING **: 11:45:09.507: Binding '<Primary>F8' failed!
WARNING  Failed to bind keyboard shortcut `<Primary>F8` to `[('alsa_card.pci-0000_00_1f.3', 'analog-output-headphones')]`

** (indicator-sound-switcher:9024): WARNING **: 11:45:09.507: Binding '<Primary>F9' failed!
WARNING  Failed to bind keyboard shortcut `<Primary>F9` to `[('alsa_card.pci-0000_00_1f.3', 'iec958-stereo-output')]`
```

**Comment by yktoo** [comment]
I'm on 22.04 LTS and all shortcuts work just fine. Must be a [libkeybinder](https://github.com/kupferlauncher/keybinder) problem.

**Comment by finsterwalder** [comment]
Same problem here... Binding fails.
Log shows:
DEBUG    .on_refresh()
DEBUG    KeyboardManager.bind_keys()
DEBUG      - Unbound keyboard shortcut `<Primary><Alt>1`
DEBUG      - Unbound keyboard shortcut `<Primary><Alt>2`
DEBUG      - Unbound keyboard shortcut `<Primary><Alt>3`

** (indicator-sound-switcher:212752): WARNING **: 09:53:40.814: Binding '<Primary><Alt>1' failed!
WARNING  Failed to bind keyboard shortcut `<Primary><Alt>1` to `[('alsa_card.pci-0000_00_1f.3', 'analog-output-speaker')]`

** (indicator-sound-switcher:212752): WARNING **: 09:53:40.814: Binding '<Primary><Alt>2' failed!
WARNING  Failed to bind keyboard shortcut `<Primary><Alt>2` to `[('alsa_card.pci-0000_00_1f.3', 'analog-output-headphones')]`

** (indicator-sound-switcher:212752): WARNING **: 09:53:40.814: Binding '<Primary><Alt>3' failed!
WARNING  Failed to bind keyboard shortcut `<Primary><Alt>3` to `[('alsa_card.pci-0000_00_1f.3', 'hdmi-output-0')]`

**Comment by yktoo** [comment]
Unfortunately, `libkeybinder` doesn't seem to report the cause of the failure for `bind()`, so I'm not sure how this can be debugged (considering I'm unable to reproduce that). The only thing I can think of is trying to pry in the system logs.

**Comment by finsterwalder** [comment]
Which window manager are you using? Wayland or X11? After a quick search it seams tha libkeybinder and Wayland don't work well together?

**Comment by OoDeLally** [comment]
I've installed Cinnamon on my Ubuntu, and it works
```
▶ indicator-sound-switcher -vv
INFO     Starting indicator application
INFO     Loaded configuration file /home/pascal/.config/indicator-sound-switcher.json
DEBUG    KeyboardManager.bind_keys()
DEBUG      - Bound keyboard shortcut `<Primary>F8` to `[('alsa_card.pci-0000_00_1f.3', 'analog-output-headphones')]`
DEBUG      - Bound keyboard shortcut `<Primary>F9` to `[('alsa_card.pci-0000_00_1f.3', 'iec958-stereo-output')]`
```

**Comment by finsterwalder** [comment]
As a workaround: You can run indicator-sound-switcher with X11 Backend and then it works:
env GDK_BACKEND=x11 indicator-sound-switcher

A real fix could be to use a GAction instead of libkeybinder, when on Wayland. :-/

**Comment by yktoo** [comment]
Indeed, it does work in a X11 session but fails on Wayland.

@finsterwalder can GAction be used for making a global shortcut?

**Comment by OoDeLally** [comment]
> As a workaround: You can run indicator-sound-switcher with X11 Backend and then it works: env GDK_BACKEND=x11 indicator-sound-switcher

Wow it does work, thanks!

**Comment by yktoo** [comment]
Conclusion: the error is caused by kupferlauncher/keybinder#17 and appears to only affect Wayland session.

The current workarounds are:
* Log into Xorg session instead of Wayland (select it on the login screen after clicking the username), or
* Start the indicator using `env GDK_BACKEND=x11 indicator-sound-switcher`
