### ISSUE TITLE
[BUG]  Indicator not present on Gnome panel

### ISSUE THREAD

**Issue by xanda-escuyer** [yktoo/indicator-sound-switcher#126]
**Describe the bug**
The indicator will not display in the Gnome panel, whether run from the command line or from the Applications panel.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run app from the Gnome menu
2. Run from command line

**Expected behaviour**
Indicator shortcut should appear in Gnome panel

**Screenshots**
![Screenshot from 2022-07-23 19-37-45](https://user-images.githubusercontent.com/15840995/180618694-ababa717-ec9b-45bb-9ecb-e9d792e4f123.png)

**Desktop (please complete the following information):**
 - OS: PureOS/Debian 11 64-bit
 - GNOME 3.38.5/Wayland
 - Sound Switcher Indicator version: 2.3.9
 - Installation source: sudo snap install indicator-sound-switcher 

**Indicator config:**
Attach the file `~/.config/indicator-sound-switcher.json` - does not seem to be available

**Indicator log:**
In order to fetch it, quit the indicator from the menu ("Quit"), open Terminal and start it again as follows: 
```bash
indicator-sound-switcher -vv
```
[AudioSwitcherRpt.txt](https://github.com/yktoo/indicator-sound-switcher/files/9174441/AudioSwitcherRpt.txt)

**Additional context**

Add any other context about the problem here:-
We've tried changing the panel colour to isolate if this is a black-on-black problem, but the icon is still not present.

**Comment by yktoo** [comment]
I see the icon is visible next to the app's name, where did you expect the icon to be?

**Comment by xanda-escuyer** [comment]
The screenshot shows what happens when the app is run from the Gnome applications panel: The  icon/menu & whirling donut appear momentarily only then to disappear entirely.
When invoked from the command line there is no such appearance (with or without the -vv switch).
In both cases the process remains running.
The response is also the same with all other extensions disabled.

**Comment by yktoo** [comment]
Do you see any other app icons in the system tray?

**Comment by xanda-escuyer** [comment]
Yes there are other icons in the system tray.
Partial screenshots attached - one with extensions enabled, the other without.

![Screenshot from 2022-07-25 18-57-56](https://user-images.githubusercontent.com/15840995/180844340-27d826d9-25a1-4db8-b1f4-7c273c42b605.png)
![Screenshot from 2022-07-25 18-57-46](https://user-images.githubusercontent.com/15840995/180844343-f1b1b128-54c7-47a0-8a1e-c55b5f380f00.png)

**Comment by glaubersm** [comment]
The icon is black on Arch Linux running gnome-shell 1:43.3-2 and indicator-sound-switcher 2.3.9-1.

![icon](https://user-images.githubusercontent.com/15967631/222913579-6b099a59-c080-4499-89da-56682cf8ec38.png)

**Comment by yktoo** [comment]
I tried to install Arch in Virtual Box but that turned out mission impossible. I someone made a bootable ISO that reproduces the problem, that'd make a good chance of the issue ever being resolved.
