### ISSUE TITLE
[Solved] Is there a way to cycle through Inputs and Outputs using a keyboard shortcut? 

### ISSUE THREAD

**Issue by WolvenSpectre** [yktoo/indicator-sound-switcher#130]
[Note Longtime Windows User trained in IT but haven't used Linux except casually and not for years.  Now migrating to Mint as my primary OS and things have changed MASSIVELY in those years, so forgive the nobleness]

I have been looking for the equivelint of [SoundSwitch](https://soundswitch.aaflalo.me/) on PC which is a mainstay of my daily workflow for using a keyboard shortcut to toggle through a list of inputs and outputs for active audio sourc
[indicator-sound-switcher.json.zip](https://github.com/yktoo/indicator-sound-switcher/files/11072393/indicator-sound-switcher.json.zip)
e/output.  Your application is very similar but I am having issues understanding the way shortcuts work, mostly due to platform differences, in your program and was hoping there was a way to configure this.

OS: Linux Mint 21.1
Kernel : 5.19.0-35
DE: Cinnamon 
Source: PPA, [installed by this method (#2) ](https://softhints.com/linux-mint-how-to-quickly-switch-sound-output-devices/#bonus1createascriptforchangeofoutput)

**Comment by yktoo** [comment]
Yes it's possible to assign the same keyboard shortcut to multiple inputs or outputs. Pressing the shortcut will switch them in order.

**Comment by WolvenSpectre** [comment]
Thank you very much this is exactly what I was looking for.
