### ISSUE TITLE
Enhancement: Default input/output

### ISSUE THREAD

**Issue by domi413** [yktoo/indicator-sound-switcher#133]
Would be cool to set a default input/output. e.g. if I connect a Bluetooth-speaker and the connection is lost, it automatically switches to a defined default output.

**Comment by yktoo** [comment]
You can do that in PulseAudio/PipeWire config already, although in a less visual way.

**Comment by yktoo** [comment]
`set-default-sink` is exactly what the Sound Switcher Indicator does when you click an output item (next to remapping all ports to that sink). This isn't what you're after as far as I can tell.

You might want to have a look at PA modules that allow to restore sinks and ports, see [Saving/restoring Settings Modules](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#savingrestoringsettingsmodules), and perhaps [module-switch-on-connect](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-switch-on-connect).

**Comment by yktoo** [comment]
Closing because there's an alternative solution available.
