### ISSUE TITLE
Output device just switched in active program, not globally

### ISSUE THREAD

**Issue by scheuerhans** [yktoo/indicator-sound-switcher#16]
When I switch the output device, it only is switched in the open program. For other programs I have to click again on the device name. This can really get out of hand when you want to listen to Youtube, then Clementine, then maybe VLC and so on.
Ubuntu 14.04
Indicator Sound Switcher 1.2.2

**Comment by yktoo** [comment]
Is this is still relevant in 2.0.1? Provisionally closing the bug.
