### ISSUE TITLE
Only HDMI output is shown in elementaryOS

### ISSUE THREAD

**Issue by richardwonka** [yktoo/indicator-sound-switcher#18]
Hello there,

I have install 1.2.2 from the ppa on elementaryOS Freya beta1. I have two entries for the internal microphone, but only one entry available for output. Luckily it's the HDMI output that I use mostly, but I'd like to be able to switch to internal speakers and headphones.

BTW: Is it possible to enable two (or more) outputs simultaneously?

**Comment by yktoo** [comment]
Digital and analog outputs belong to different profiles, and ports belonging to inactive profiles don't show up in the menu. It's a known limitation of the app (#3).

PS. I won't be able to test it under elementary OS.
