### ISSUE TITLE
PPA not working?

### ISSUE THREAD

**Issue by faelsoto** [yktoo/indicator-sound-switcher#20]
First of all, thanks for such this amazing piece of software, I switch between my HDMI device's audio and headphones, and each time opening the sound control panel feels like something's missing.

However, it seems that the PPA is broken, as I can't install it on Ubuntu 15.10, am I doing something wrong?

Thanks.

**Comment by yktoo** [comment]
Copied `indicator-sound-switcher - 1.2.2ubuntu0-gtk3ppa0-1` to the `Wily` series.
