### ISSUE TITLE
Possibly missing the "multichannel output + multichannel input" profile?

### ISSUE THREAD

**Issue by tdu-audio** [yktoo/indicator-sound-switcher#22]
We don't know where we should be starting, but basically we are having some issues while using RME FireFace UFX (in USB Class-Compliant Mode) on UbuntuStudio 16.04LTS. Normally, the host runs _jackd_ and is used as a DA-transport by some amateur audiophiles. The issue appeared just as we decided to use _mataa_ for some performance tests on amplifiers and loudspeakers our members build.

Because the setup we came up with requires Output9,10 (8,9 on ALSA) enabled, we need 22ch output even when _jackd_ has been stopped. Therefore, maintaining the output of the device operating in `Altset 2` (as shown in `cat /proc/asound/card1/stream0`) is a must.

After finding out that changing profiles in _indicator-sound_ was doing something about it, we then wanted to know ways for enabling multichannel-input and multichannel-output. 

```
Playback:
    Status: Stop
    Interface 1
        Altset 1
        Format: S24_3LE
        Channels: 2
        Endpoint: 1 OUT (ASYNC)
        Rates: 44100, 48000, 88200, 96000, 176400, 192000
        Data packet interval: 125 us
    Interface 1
        Altset 2
        Format: S24_3LE
        Channels: 22
        Endpoint: 1 OUT (ASYNC)
        Rates: 44100, 48000, 88200, 96000, 176400, 192000
        Data packet interval: 125 us

Capture:
    Status: Stop
    Interface 2
        Altset 1
        Format: S24_3LE
        Channels: 22
        Endpoint: 2 IN (ASYNC)
        Rates: 44100, 48000, 88200, 96000, 176400, 192000
        Data packet interval: 125 us
    Interface 2
        Altset 2
        Format: S24_3LE
        Channels: 12
        Endpoint: 2 IN (ASYNC)
        Rates: 44100, 48000, 88200, 96000, 176400, 192000
        Data packet interval: 125 us
```

Because the host runs _jackd_ normally for audio playback (and then _PulseAudio Jack Sink_ is in effect), this is not really a problem for us - we see all 22ch when running _jackd_. The problem is, we now want to use _Octave_ to enable the use of _mataa_ for some audio analysis. For technical reasons, we have decided that _jackd_ should be stopped while using _mataa_. 
The issue begins when we start talking about setting Output-9, Output-10, Input-9 and Input-10 of UFX as the default device to the system, as to be defined in `/etc/asound.conf`.

Sorry for a non-descriptive comment, but we hope you'll ask us for detailed descriptions of the situation as needed.

Including mentions to @tahiro86j in your replies should make things go smoother.

Thanks in advance.

**Comment by yktoo** [comment]
Okay that's a lot of unfamiliar words for me :) @tdu-audio @tahiror86j Question no. 1: is this issue still relevant with the latest release of SSI?
