### ISSUE TITLE
ERROR: '~yktooo' user or team does not exist.

### ISSUE THREAD

**Issue by escopecz** [yktoo/indicator-sound-switcher#25]
I tried to follow the install instructions:

https://github.com/yktoo/indicator-sound-switcher/blob/master/INSTALL#L13

But I get this:
```
$ sudo apt-add-repository ppa:yktooo/ppa
Cannot add PPA: 'ppa:~yktooo/ubuntu/ppa'.
ERROR: '~yktooo' user or team does not exist.
```
What is the problem?

**Comment by nifr** [comment]
![screen shot 2016-09-26 at 16 34 06](https://cloud.githubusercontent.com/assets/851258/18838270/26907c40-8407-11e6-801c-737299c57de8.png)

Launchpad is down for maintenance. There have been several downtimes over the last days.

You should be able to follow the instructions once they are back online. Just check their [status updates](https://twitter.com/launchpadstatus) regularly. 

I guess this issue will resolve itself ;)
