### ISSUE TITLE
Allow to specify a preferred profile for the port

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [yktoo/indicator-sound-switcher#26]
I usually switch around between _Digital Output_ and _Speakers_, but for the speakers I choose the `Analog Surround 4.0 Output` instead of the default `Analog Stereo Output`.

It would be awesome if I could choose those modes directly from the indicator or, when switching back to the _Speakers_, keep the previous value.

**Comment by yktoo** [comment]
Could you show a screenshot of what you mean exactly?

**Comment by RicardoEPRodrigues** [comment]
Here it goes.
![selectoutputmodes](https://cloud.githubusercontent.com/assets/7673578/18843036/201ac99e-840f-11e6-914c-9d165c883b7f.png)

**Comment by yktoo** [comment]
Thanks, I see now. Well, that's one of the most complex matters about switching profiles. GCC Sound Panel tried to implement some "artificial intelligence" there, which is quite involved. In SSI I simply pick the profile with the highest priority (which is obviously not what you want in this case).

I think further improvements would probably be best implemented via a config file, where you could specify your preferred profile per device.

**Comment by RicardoEPRodrigues** [comment]
Maybe a [flyout submenu](http://sevenspark.com/docs/ubermenu-3/settings/submenu/types) would do the trick?

With a clickable title with the default behavior as it is now.

**Comment by yktoo** [comment]
Those are not supported by GTK, as far as I'm aware :)

**Comment by RicardoEPRodrigues** [comment]
I still didn't have a chance to get into GTK, but there are submenus look for example at [ClassicMenu](http://www.florian-diesch.de/software/classicmenu-indicator/).

I think [this post](http://askubuntu.com/questions/154286/how-to-add-sub-menus-in-appindicators) should help you do it, when you have the time.

**Comment by yktoo** [comment]
Submenus are no problem at all, they're supported.

**Comment by RicardoEPRodrigues** [comment]
Then what did you mean by 

> Those are not supported by GTK, as far as I'm aware :)

**Comment by yktoo** [comment]
Sorry, I was referring to flyout submenus you mentioned.

**Comment by RicardoEPRodrigues** [comment]
It's almost the same thing. 😀 Will submenus solve the problem?

Both the config file and the submenu options seem like solutions.

**Comment by yktoo** [comment]
Fixed in 2.1.1.
