### ISSUE TITLE
Replace the original sound indicator

### ISSUE THREAD

**Issue by kogaba** [yktoo/indicator-sound-switcher#27]
First of all thanks for the good job :-)
I would like to suggest some improvement, to the program, which are maybe too much, but maybe you'll find these interesting, and hopefully implement it.

I like keep stuff as compact as possible, so I'd like one sound indicator.
So if you implemented the "mute", "volume" and "sound preferences..." menus I can switch off the default indicator. And well, the indicator icon, should be like the current system indicator.
I never change inputs, so it'd be also cool if I can hide the input selection menus.

Maybe just add input/output selection possibilities, to the default sound indicator? :)
Thanks

**Comment by yktoo** [comment]
Thanks for your input. Unfortunately, this is exactly what I have been trying to avoid, to create yet another "Sound Indicator" :)

The whole idea of this application is provide a quick way of switching inputs and outputs, not to replace the (quite functional) existing indicator. So I'm afraid this isn't going to happen, sorry for that.

On the contrary, switching the entire input and/or output section is a good idea I think. It'll boil down to the mapping feature that is on my todo list already.
