### ISSUE TITLE
Doesn't work on my bluetooth headset

### ISSUE THREAD

**Issue by alecive** [yktoo/indicator-sound-switcher#29]
Hello @yktoo ,

first and foremost, I am using the indicator on Ubuntu 14.04. I know that it is not supported, but I cannot upgrade and the indicator apparently is working fine even on older Ubuntu versions.

Basically what happens is that if I connect my bluetooth headset on the machine , the indicator is not refreshed even if I click on the `refresh` button. Only when I open the sound settings, then the indicator auto-refreshes and the headset is correctly identified.

I can provide pictures if it is not clear!

**Comment by yktoo** [comment]
I guess the debug output from `indicator-sound-switcher -vv` would be of better use.
