### ISSUE TITLE
Make installation from the source tree possible

### ISSUE THREAD

**Issue by yktoo** [yktoo/indicator-sound-switcher#35]
As mentioned in #34, the original source code misses the `locale` dir (which is only generated by `build_package`), that makes installation fail.

Probably need to add some custom `setup.py` command and update the installation instructions.

**Comment by PeterMitrano** [comment]
this also happened to me on ubuntu 14.04

**Comment by yktoo** [comment]
Fixed in 2.1.1. .po files are compiled now as a part of standard install.
