### ISSUE TITLE
Keyboard shortcuts to switch sound

### ISSUE THREAD

**Issue by 001ben** [yktoo/indicator-sound-switcher#38]
I would love to be able to set some hotkeys for switching to particular sound outputs. Even if you could just bind a keyboard shortcut to a command that would pass through to the indicator sound switcher

**Comment by yktoo** [comment]
I believe the best solution to this is binding any keys you want via Gnome Control Center to `pacmd`. I don't think this functionality belongs with this indicator.

**Comment by yktoo** [comment]
After some deliberation I think this might still be useful, especially for a non-experienced user.

**Comment by yktoo** [comment]
Resolved in 2.3.0.
