### ISSUE TITLE
Switching after suspend

### ISSUE THREAD

**Issue by Aivenho** [yktoo/indicator-sound-switcher#41]
I'm not sure is it your app problem or just my hardware, but after suspend I'm not able to switch to HDMI/DisplayPort... Ubuntu 16.04, Sound Switcher Indicator 2.1.1.

**Comment by yktoo** [comment]
Could you run `indicator-sound-switcher -vv`, reproduce the situation and post the console output here?

**Comment by Aivenho** [comment]
Sorry, I think it is kernel issue after suspend, I can't switch them even with sound system settings applet.
