### ISSUE TITLE
Crash when restarting Pulseaudio

### ISSUE THREAD

**Issue by pabloab** [yktoo/indicator-sound-switcher#45]
I was trying [paprefs to output simultaneously](http://askubuntu.com/questions/78174/play-sound-through-two-or-more-outputs-devices) when notice indicator-sound-switcher crash always I (kill and)restart Pulseaudio (`pulseaudio -k`).
Using v2.1.1, Ubuntu 16.04 and pulseaudio 8.0.

**Comment by yktoo** [comment]
Well yes, SSI doesn't account for PulseAudio dying while it's running. For me, it actually shows a critical error `CRI Context failed.` I'm not sure it's a problem really, obviously a sound switcher cannot function without the sound server. Perhaps exiting after PA has gone offline would be more consistent.

**Comment by pabloab** [comment]
Maybe instead of crashing could handle/catch the situation, for example keep waiting to PA to come back (as usually happens after a `pulseaudio -k`). Also maybe could send a warning to [notify-osd](https://launchpad.net/notify-osd).

**Comment by yktoo** [comment]
I wholeheartedly agree that nothing should ever crash, but in my case there was no crash, just a log message with CRITICAL status. I'll think what can be done here.
