### ISSUE TITLE
Add LADSPA plugins managment

### ISSUE THREAD

**Issue by vktRus** [yktoo/indicator-sound-switcher#49]
Add LADSPA Pulseaudio plugins managment. For example, [Calf Jack host](http://zenway.ru/page/calf).

**Comment by yktoo** [comment]
What does it have to do with sound switching?

**Comment by vktRus** [comment]
[RU] При задействовании плагинов создаются новые входы-выходы звука.
Переключатель входов-выходов уже есть. Осталось только навесить плагины со своими настройками и в нужной последовательности.
Умерший проект http://zenway.ru/page/veromix подхватить или сделать лучше.
[EN] In the activation of the plugins create new inputs and outputs sound.
Switch the inputs / outputs are already there. It remains only to hang a plugin with its own settings and in the correct sequence.

**Comment by yktoo** [comment]
I'm afraid that's a bridge too far for this indicator. This functionality is more suitable for some separate application like `pulseefects`, the main purpose of this one, however, is make sound stream switching easy.
