### ISSUE TITLE
2 HDMI Outputs

### ISSUE THREAD

**Issue by xSeekTruthx** [yktoo/indicator-sound-switcher#53]
Ubuntu 14.04
Sound Switcher 1.2.2

I have...
HDMI / Display port
HDMI / Display port 2 

..In my output sources in the built in Sound setting. However Sound Switcher only recognizes the one that is currently selected. It will not show both HDMI sound outputs in the menu. I tried refreshing and restarting. Any idea how to make sure it always shows both HDMI outputs like it does in my Sound settings?

Thank you,

**Comment by yktoo** [comment]
SSI didn't support sound card profiles before version 2.0.1. You will need  to upgrade in order to properly support digital in-/outputs like HDMI (also keep in mind SSI isn't supported on Ubuntu prior to 14.10 anymore).
