### ISSUE TITLE
pulseaudio-module-jack not supported ?

### ISSUE THREAD

**Issue by timophey** [yktoo/indicator-sound-switcher#54]
When I start Jack in my 14.04 with switcher 1.2.2, it appears in Sound properties and in this indicator too.
But in 16.04 switcher 2.1.1 doesn't see PulseAudio JACK Sink.

**Comment by yktoo** [comment]
Unfortunately I'm not familiar with JACK. Could you re-check with the most recent app version and come back if the issue still holds?
