### ISSUE TITLE
Provide package for Ubuntu 17.10 Artful

### ISSUE THREAD

**Issue by kerosan** [yktoo/indicator-sound-switcher#58]
E: Репозиторий «http://ppa.launchpad.net/yktooo/ppa/ubuntu artful Release» не содержит файла Release.
N: Обновление из этого репозитория нельзя выполнить безопасным способом, и поэтому по умолчанию он отключён.
N: Смотрите справочную страницу apt-secure(8) о создании репозитория и настройке пользователя.

**Comment by yktoo** [comment]
Copied to 17.10 Artful series.

**Comment by kerosan** [comment]
👍
