### ISSUE TITLE
CRI context failed

### ISSUE THREAD

**Issue by theaquacadet** [yktoo/indicator-sound-switcher#59]
I've been messing around with jack recently and now indicator-sound-switcher will not launch. verbose log: 

`INF Configuration file /home/jake/.config/indicator-sound-switcher.json not found, falling back to defaults`

`CRI Context failed`

Reinstall does not help. I can't find anything about CRI context with some googling. any help would be appreciated.

**Comment by yktoo** [comment]
`CRI` is short for 'CRITICAL' (like other log message can be classified `DEB` for DEBUG or `INF` for INFO). And "Context failed" indicates the application failed to establish a connection with the PulseAudio server.

Is it still relevant? If so, please reopen (and add more details please).
