### ISSUE TITLE
ubuntu 17.10 , app opened but not showing the icon

### ISSUE THREAD

**Issue by ijash** [yktoo/indicator-sound-switcher#62]
as the post title, please advise.

```INF Loaded configuration file /home/ijash/.config/indicator-sound-switcher.json
INF Context connected
DEB   + Card[0] added: `alsa_card.pci-0000_01_00.1`
DEB     + Card profile added: `output:hdmi-stereo` (`Digital Stereo (HDMI) Output`), 1 sinks, 0 sources, priority: 5400 -- Active
DEB     + Card profile added: `output:hdmi-stereo-extra1` (`Digital Stereo (HDMI 2) Output`), 1 sinks, 0 sources, priority: 5200
DEB     + Card profile added: `output:hdmi-surround-extra1` (`Digital Surround 5.1 (HDMI 2) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-surround71-extra1` (`Digital Surround 7.1 (HDMI 2) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-stereo-extra2` (`Digital Stereo (HDMI 3) Output`), 1 sinks, 0 sources, priority: 5200
DEB     + Card profile added: `output:hdmi-surround-extra2` (`Digital Surround 5.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-surround71-extra2` (`Digital Surround 7.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-stereo-extra3` (`Digital Stereo (HDMI 4) Output`), 1 sinks, 0 sources, priority: 5200
DEB     + Card profile added: `output:hdmi-surround-extra3` (`Digital Surround 5.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-surround71-extra3` (`Digital Surround 7.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEB     + Card port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; direction: 1; available: Yes
DEB       . Supported profile: `output:hdmi-stereo`
DEB     + Card port added: `hdmi-output-1` (`HDMI / DisplayPort 2`); priority: 5800; direction: 1; available: No
DEB       . Supported profile: `output:hdmi-stereo-extra1`
DEB       . Supported profile: `output:hdmi-surround-extra1`
DEB       . Supported profile: `output:hdmi-surround71-extra1`
DEB     + Card port added: `hdmi-output-2` (`HDMI / DisplayPort 3`); priority: 5700; direction: 1; available: No
DEB       . Supported profile: `output:hdmi-stereo-extra2`
DEB       . Supported profile: `output:hdmi-surround-extra2`
DEB       . Supported profile: `output:hdmi-surround71-extra2`
DEB     + Card port added: `hdmi-output-3` (`HDMI / DisplayPort 4`); priority: 5600; direction: 1; available: No
DEB       . Supported profile: `output:hdmi-stereo-extra3`
DEB       . Supported profile: `output:hdmi-surround-extra3`
DEB       . Supported profile: `output:hdmi-surround71-extra3`
DEB   + Card[1] added: `alsa_card.usb-Yamaha_Corporation_Steinberg_CI2_-01`
DEB     + Card profile added: `input:analog-stereo` (`Analog Stereo Input`), 0 sinks, 1 sources, priority: 60
DEB     + Card profile added: `input:iec958-stereo` (`Digital Stereo (IEC958) Input`), 0 sinks, 1 sources, priority: 55
DEB     + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 6000
DEB     + Card profile added: `output:analog-stereo+input:analog-stereo` (`Analog Stereo Duplex`), 1 sinks, 1 sources, priority: 6060 -- Active
DEB     + Card profile added: `output:analog-stereo+input:iec958-stereo` (`Analog Stereo Output + Digital Stereo (IEC958) Input`), 1 sinks, 1 sources, priority: 6055
DEB     + Card profile added: `output:iec958-stereo` (`Digital Stereo (IEC958) Output`), 1 sinks, 0 sources, priority: 5500
DEB     + Card profile added: `output:iec958-stereo+input:analog-stereo` (`Digital Stereo (IEC958) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5560
DEB     + Card profile added: `output:iec958-stereo+input:iec958-stereo` (`Digital Stereo Duplex (IEC958)`), 1 sinks, 1 sources, priority: 5555
DEB     + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEB     + Card port added: `analog-input` (`Analog Input`); priority: 10000; direction: 2; available: Yes
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `iec958-stereo-input` (`Digital Input (S/PDIF)`); priority: 0; direction: 2; available: Yes
DEB       . Supported profile: `input:iec958-stereo`
DEB       . Supported profile: `output:analog-stereo+input:iec958-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:iec958-stereo`
DEB     + Card port added: `analog-output` (`Analog Output`); priority: 9900; direction: 1; available: Yes
DEB       . Supported profile: `output:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:iec958-stereo`
DEB     + Card port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEB       . Supported profile: `output:iec958-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:iec958-stereo`
DEB   + Card[2] added: `alsa_card.pci-0000_00_1f.3`
DEB     + Card profile added: `input:analog-stereo` (`Analog Stereo Input`), 0 sinks, 1 sources, priority: 60
DEB     + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 6000
DEB     + Card profile added: `output:analog-stereo+input:analog-stereo` (`Analog Stereo Duplex`), 1 sinks, 1 sources, priority: 6060
DEB     + Card profile added: `output:analog-surround-21` (`Analog Surround 2.1 Output`), 1 sinks, 0 sources, priority: 800
DEB     + Card profile added: `output:analog-surround-21+input:analog-stereo` (`Analog Surround 2.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 860
DEB     + Card profile added: `output:analog-surround-40` (`Analog Surround 4.0 Output`), 1 sinks, 0 sources, priority: 700
DEB     + Card profile added: `output:analog-surround-40+input:analog-stereo` (`Analog Surround 4.0 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 760
DEB     + Card profile added: `output:analog-surround-41` (`Analog Surround 4.1 Output`), 1 sinks, 0 sources, priority: 800
DEB     + Card profile added: `output:analog-surround-41+input:analog-stereo` (`Analog Surround 4.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 860
DEB     + Card profile added: `output:analog-surround-50` (`Analog Surround 5.0 Output`), 1 sinks, 0 sources, priority: 700
DEB     + Card profile added: `output:analog-surround-50+input:analog-stereo` (`Analog Surround 5.0 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 760
DEB     + Card profile added: `output:analog-surround-51` (`Analog Surround 5.1 Output`), 1 sinks, 0 sources, priority: 800
DEB     + Card profile added: `output:analog-surround-51+input:analog-stereo` (`Analog Surround 5.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 860
DEB     + Card profile added: `output:analog-surround-71` (`Analog Surround 7.1 Output`), 1 sinks, 0 sources, priority: 700
DEB     + Card profile added: `output:analog-surround-71+input:analog-stereo` (`Analog Surround 7.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 760
DEB     + Card profile added: `output:iec958-stereo` (`Digital Stereo (IEC958) Output`), 1 sinks, 0 sources, priority: 5500
DEB     + Card profile added: `output:iec958-stereo+input:analog-stereo` (`Digital Stereo (IEC958) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5560 -- Active
DEB     + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEB     + Card port added: `analog-input-front-mic` (`Front Microphone`); priority: 8500; direction: 2; available: No
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `analog-input-rear-mic` (`Rear Microphone`); priority: 8200; direction: 2; available: No
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `analog-input-linein` (`Line In`); priority: 8100; direction: 2; available: No
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `analog-output-lineout` (`Line Out`); priority: 9900; direction: 1; available: No
DEB       . Supported profile: `output:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB     + Card port added: `analog-output-headphones` (`Headphones`); priority: 9000; direction: 1; available: No
DEB       . Supported profile: `output:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB     + Card port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEB       . Supported profile: `output:iec958-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB   + Source[2] added: `alsa_input.usb-Yamaha_Corporation_Steinberg_CI2_-01.analog-stereo`, card 1
DEB     + Source port added: `analog-input` (`Analog Input`); priority: 10000; available: Yes
DEB     * Activated source port `analog-input`
DEB   + Source[4] added: `alsa_input.pci-0000_00_1f.3.analog-stereo`, card 2
DEB     + Source port added: `analog-input-front-mic` (`Front Microphone`); priority: 8500; available: No
DEB     + Source port added: `analog-input-rear-mic` (`Rear Microphone`); priority: 8200; available: No
DEB     + Source port added: `analog-input-linein` (`Line In`); priority: 8100; available: No
DEB     * Activated source port `analog-input-front-mic`
DEB   + Sink[0] added: `alsa_output.pci-0000_01_00.1.hdmi-stereo`, card 0
DEB     + Sink port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; available: Yes
DEB     * Activated sink port `hdmi-output-0`
DEB   + Sink[1] added: `alsa_output.usb-Yamaha_Corporation_Steinberg_CI2_-01.analog-stereo`, card 1
DEB     + Sink port added: `analog-output` (`Analog Output`); priority: 9900; available: Yes
DEB     * Activated sink port `analog-output`
DEB   + Sink[2] added: `alsa_output.pci-0000_00_1f.3.iec958-stereo`, card 2
DEB     + Sink port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; available: Yes
DEB     * Activated sink port `iec958-stereo-output`
DEB * Activated sink: `alsa_output.pci-0000_01_00.1.hdmi-stereo`
DEB * Activated source: `alsa_input.pci-0000_00_1f.3.analog-stereo`

(indicator-sound-switcher:8573): libappindicator-WARNING **: Unable to connect to the Notification Watcher: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.kde.StatusNotifierWatcher' on object at path /StatusNotifierWatcher

```

**Comment by ijash** [comment]
`INF Loaded configuration file /home/ijash/.config/indicator-sound-switcher.json
INF Context connected
DEB   + Card[0] added: `alsa_card.pci-0000_01_00.1`
DEB     + Card profile added: `output:hdmi-stereo` (`Digital Stereo (HDMI) Output`), 1 sinks, 0 sources, priority: 5400 -- Active
DEB     + Card profile added: `output:hdmi-stereo-extra1` (`Digital Stereo (HDMI 2) Output`), 1 sinks, 0 sources, priority: 5200
DEB     + Card profile added: `output:hdmi-surround-extra1` (`Digital Surround 5.1 (HDMI 2) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-surround71-extra1` (`Digital Surround 7.1 (HDMI 2) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-stereo-extra2` (`Digital Stereo (HDMI 3) Output`), 1 sinks, 0 sources, priority: 5200
DEB     + Card profile added: `output:hdmi-surround-extra2` (`Digital Surround 5.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-surround71-extra2` (`Digital Surround 7.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-stereo-extra3` (`Digital Stereo (HDMI 4) Output`), 1 sinks, 0 sources, priority: 5200
DEB     + Card profile added: `output:hdmi-surround-extra3` (`Digital Surround 5.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `output:hdmi-surround71-extra3` (`Digital Surround 7.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 100
DEB     + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEB     + Card port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; direction: 1; available: Yes
DEB       . Supported profile: `output:hdmi-stereo`
DEB     + Card port added: `hdmi-output-1` (`HDMI / DisplayPort 2`); priority: 5800; direction: 1; available: No
DEB       . Supported profile: `output:hdmi-stereo-extra1`
DEB       . Supported profile: `output:hdmi-surround-extra1`
DEB       . Supported profile: `output:hdmi-surround71-extra1`
DEB     + Card port added: `hdmi-output-2` (`HDMI / DisplayPort 3`); priority: 5700; direction: 1; available: No
DEB       . Supported profile: `output:hdmi-stereo-extra2`
DEB       . Supported profile: `output:hdmi-surround-extra2`
DEB       . Supported profile: `output:hdmi-surround71-extra2`
DEB     + Card port added: `hdmi-output-3` (`HDMI / DisplayPort 4`); priority: 5600; direction: 1; available: No
DEB       . Supported profile: `output:hdmi-stereo-extra3`
DEB       . Supported profile: `output:hdmi-surround-extra3`
DEB       . Supported profile: `output:hdmi-surround71-extra3`
DEB   + Card[1] added: `alsa_card.usb-Yamaha_Corporation_Steinberg_CI2_-01`
DEB     + Card profile added: `input:analog-stereo` (`Analog Stereo Input`), 0 sinks, 1 sources, priority: 60
DEB     + Card profile added: `input:iec958-stereo` (`Digital Stereo (IEC958) Input`), 0 sinks, 1 sources, priority: 55
DEB     + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 6000
DEB     + Card profile added: `output:analog-stereo+input:analog-stereo` (`Analog Stereo Duplex`), 1 sinks, 1 sources, priority: 6060 -- Active
DEB     + Card profile added: `output:analog-stereo+input:iec958-stereo` (`Analog Stereo Output + Digital Stereo (IEC958) Input`), 1 sinks, 1 sources, priority: 6055
DEB     + Card profile added: `output:iec958-stereo` (`Digital Stereo (IEC958) Output`), 1 sinks, 0 sources, priority: 5500
DEB     + Card profile added: `output:iec958-stereo+input:analog-stereo` (`Digital Stereo (IEC958) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5560
DEB     + Card profile added: `output:iec958-stereo+input:iec958-stereo` (`Digital Stereo Duplex (IEC958)`), 1 sinks, 1 sources, priority: 5555
DEB     + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEB     + Card port added: `analog-input` (`Analog Input`); priority: 10000; direction: 2; available: Yes
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `iec958-stereo-input` (`Digital Input (S/PDIF)`); priority: 0; direction: 2; available: Yes
DEB       . Supported profile: `input:iec958-stereo`
DEB       . Supported profile: `output:analog-stereo+input:iec958-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:iec958-stereo`
DEB     + Card port added: `analog-output` (`Analog Output`); priority: 9900; direction: 1; available: Yes
DEB       . Supported profile: `output:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:iec958-stereo`
DEB     + Card port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEB       . Supported profile: `output:iec958-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:iec958-stereo`
DEB   + Card[2] added: `alsa_card.pci-0000_00_1f.3`
DEB     + Card profile added: `input:analog-stereo` (`Analog Stereo Input`), 0 sinks, 1 sources, priority: 60
DEB     + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 6000
DEB     + Card profile added: `output:analog-stereo+input:analog-stereo` (`Analog Stereo Duplex`), 1 sinks, 1 sources, priority: 6060
DEB     + Card profile added: `output:analog-surround-21` (`Analog Surround 2.1 Output`), 1 sinks, 0 sources, priority: 800
DEB     + Card profile added: `output:analog-surround-21+input:analog-stereo` (`Analog Surround 2.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 860
DEB     + Card profile added: `output:analog-surround-40` (`Analog Surround 4.0 Output`), 1 sinks, 0 sources, priority: 700
DEB     + Card profile added: `output:analog-surround-40+input:analog-stereo` (`Analog Surround 4.0 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 760
DEB     + Card profile added: `output:analog-surround-41` (`Analog Surround 4.1 Output`), 1 sinks, 0 sources, priority: 800
DEB     + Card profile added: `output:analog-surround-41+input:analog-stereo` (`Analog Surround 4.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 860
DEB     + Card profile added: `output:analog-surround-50` (`Analog Surround 5.0 Output`), 1 sinks, 0 sources, priority: 700
DEB     + Card profile added: `output:analog-surround-50+input:analog-stereo` (`Analog Surround 5.0 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 760
DEB     + Card profile added: `output:analog-surround-51` (`Analog Surround 5.1 Output`), 1 sinks, 0 sources, priority: 800
DEB     + Card profile added: `output:analog-surround-51+input:analog-stereo` (`Analog Surround 5.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 860
DEB     + Card profile added: `output:analog-surround-71` (`Analog Surround 7.1 Output`), 1 sinks, 0 sources, priority: 700
DEB     + Card profile added: `output:analog-surround-71+input:analog-stereo` (`Analog Surround 7.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 760
DEB     + Card profile added: `output:iec958-stereo` (`Digital Stereo (IEC958) Output`), 1 sinks, 0 sources, priority: 5500
DEB     + Card profile added: `output:iec958-stereo+input:analog-stereo` (`Digital Stereo (IEC958) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5560 -- Active
DEB     + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEB     + Card port added: `analog-input-front-mic` (`Front Microphone`); priority: 8500; direction: 2; available: No
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `analog-input-rear-mic` (`Rear Microphone`); priority: 8200; direction: 2; available: No
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `analog-input-linein` (`Line In`); priority: 8100; direction: 2; available: No
DEB       . Supported profile: `input:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB     + Card port added: `analog-output-lineout` (`Line Out`); priority: 9900; direction: 1; available: No
DEB       . Supported profile: `output:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-21`
DEB       . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-40`
DEB       . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-41`
DEB       . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-50`
DEB       . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-51`
DEB       . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEB       . Supported profile: `output:analog-surround-71`
DEB       . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEB     + Card port added: `analog-output-headphones` (`Headphones`); priority: 9000; direction: 1; available: No
DEB       . Supported profile: `output:analog-stereo`
DEB       . Supported profile: `output:analog-stereo+input:analog-stereo`
DEB     + Card port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEB       . Supported profile: `output:iec958-stereo`
DEB       . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEB   + Source[2] added: `alsa_input.usb-Yamaha_Corporation_Steinberg_CI2_-01.analog-stereo`, card 1
DEB     + Source port added: `analog-input` (`Analog Input`); priority: 10000; available: Yes
DEB     * Activated source port `analog-input`
DEB   + Source[4] added: `alsa_input.pci-0000_00_1f.3.analog-stereo`, card 2
DEB     + Source port added: `analog-input-front-mic` (`Front Microphone`); priority: 8500; available: No
DEB     + Source port added: `analog-input-rear-mic` (`Rear Microphone`); priority: 8200; available: No
DEB     + Source port added: `analog-input-linein` (`Line In`); priority: 8100; available: No
DEB     * Activated source port `analog-input-front-mic`
DEB   + Sink[0] added: `alsa_output.pci-0000_01_00.1.hdmi-stereo`, card 0
DEB     + Sink port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; available: Yes
DEB     * Activated sink port `hdmi-output-0`
DEB   + Sink[1] added: `alsa_output.usb-Yamaha_Corporation_Steinberg_CI2_-01.analog-stereo`, card 1
DEB     + Sink port added: `analog-output` (`Analog Output`); priority: 9900; available: Yes
DEB     * Activated sink port `analog-output`
DEB   + Sink[2] added: `alsa_output.pci-0000_00_1f.3.iec958-stereo`, card 2
DEB     + Sink port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; available: Yes
DEB     * Activated sink port `iec958-stereo-output`
DEB * Activated sink: `alsa_output.pci-0000_01_00.1.hdmi-stereo`
DEB * Activated source: `alsa_input.pci-0000_00_1f.3.analog-stereo`

(indicator-sound-switcher:8573): libappindicator-WARNING **: Unable to connect to the Notification Watcher: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.kde.StatusNotifierWatcher' on object at path /StatusNotifierWatcher

`

**Comment by yktoo** [comment]
Which desktop environment are you using?

**Comment by ijash** [comment]
default ubuntu 17.10 DE.. GNOME. somehow, it  shows back. and sometimes dissappear..

**Comment by turbohz** [comment]
Same issue here.

```
/λ/ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

**Comment by yktoo** [comment]
I have the impression it's rather a `libappindicator`'s bug since I observe it with other icons (e.g. Dropbox), but not with the Sound Switcher. Also the code for registering the app icon is pretty straightforward so I can hardly imagine what can go wrong there.

**Comment by turbohz** [comment]
Yes, I have noticed other icons not showing (redshift-gtk, for instance)

**Comment by yktoo** [comment]
Ditching `indicator-application` [should help](https://askubuntu.com/questions/966987/indicator-icons-do-not-appear-after-upgrade-to-ubuntu-17-10):
```
sudo apt purge indicator-application
killall indicator-application-service
```
