### ISSUE TITLE
Change the top bar icon colour?

### ISSUE THREAD

**Issue by bobpardoe** [yktoo/indicator-sound-switcher#69]
Is there a way I can change the colour (or icon) to be white so it is easier to see?

It's the dark grey circle between the date and the mkchromecast icon

Thanks

![screenshot from 2019-01-31 17-53-09](https://user-images.githubusercontent.com/11973854/52074208-46c78300-2581-11e9-992a-ff031a2cc5f0.png)

**Comment by yktoo** [comment]
Hmm, are you sure it's the indicator's icon? I doesn't look like one. What DE are you using?

There are 3 different icon versions shipped with the indicator: a dark, a light and a versatile one. You can play with them.
```
/usr/share/icons/hicolor/22x22/status/indicator-sound-switcher.svg
/usr/share/icons/hicolor/scalable/status/indicator-sound-switcher.svg
/usr/share/icons/ubuntu-mono-dark/status/22/indicator-sound-switcher.svg
/usr/share/icons/ubuntu-mono-light/status/22/indicator-sound-switcher.svg
```

**Comment by bobpardoe** [comment]
I understand now. I was using an alternative icon set to the ones provided with the app.
Thanks for the response.
