### ISSUE TITLE
No icon in notification area but there is a blank space were icon should be Mint 19.1 MATE

### ISSUE THREAD

**Issue by adrummer354** [yktoo/indicator-sound-switcher#71]
I installed 2.2.0 on Linux mint 19.1 MATE but do not have an icon in the system tray when the application is open. It opens a blank space where there should be an icon so I can right click that space to execute functions as needed but no icon is there.

**Comment by yktoo** [comment]
The package install icons into the following directories:
```
share/icons/ubuntu-mono-dark/status/22
share/icons/ubuntu-mono-light/status/22
share/icons/hicolor/22x22/status
share/icons/hicolor/scalable/status
```

I guess Mint doesn't use any of them. So you would need to symlink or copy the appropriate icon file into a location recognised by Mint. And then run `sudo update-icon-caches /usr/share/icons/*`.

**Comment by yktoo** [comment]
Hi @adrummer354, dod you manage do fix the issue with the solution I provided?
