### ISSUE TITLE
Checkboxes instead of Radio Buttons in Menu

### ISSUE THREAD

**Issue by JoeJoeTV** [yktoo/indicator-sound-switcher#83]
I don't know how it's intended, but I'm using Linux Mint 19.3 Cinnamon and the Sound Switcher menu is showing checkboxes for the device, which doesn't seem right to me. After installing, it showed Radio Buttons, but now it only shows checkboxes.

Can there be multiple selected, and if yes, is there an option to get the radio buttons back, so the switching is easier?

So when I try to switch to another device, I have to uncheck to old one and check the new one multiple times to get it to work.

![Unbenannt](https://user-images.githubusercontent.com/34209417/74569321-6f4ad100-4f7a-11ea-9d59-6e5db66a49ba.png)

**Comment by yktoo** [comment]
I'm not really sure what can cause that. Sound Switcher Indicator always creates instances of Gtk.RadioMenuItem. So to me it looks like a quirk in Mint's GTK+ implementation.

You're also saying it did show radio buttons at first, so maybe you've installed some library or theme that overrides that?

**Comment by yktoo** [comment]
Closing for now because of insufficient input. Please re-open if you have more details.
