### ISSUE TITLE
Request | Make an option to change Apps volume

### ISSUE THREAD

**Issue by ijaure299** [yktoo/indicator-sound-switcher#84]
First of all I just want to say that your tool is what made me switch to linux! 

Love it! 

Secondly it would be amazing if there was an option to change the volume of the apps that playing.

thank you for your hard work

**Comment by pohmelie** [comment]
Vote on this. At least input/output volumes. I've tried to do this myself, but it looks like that scale widget can't be inserted into menu. https://stackoverflow.com/questions/37634598/pygobject-scale-range-as-gtk-menuitem

**Comment by yktoo** [comment]
I don't think adjusting volume belongs to a sound switcher to be honest.
1. It will bloat the indicator, which serves a pretty specific purpose, which is switching sound ports.
2. It is problematic to do properly (it's indeed isn't possible to add anything but regular items to indicator menu)

Adding this will effectively turn SSI into a like of `pavucontrol`, which I believe is a perfect tool for the mentioned task.
