### ISSUE TITLE
Symbolic icons colouring

### ISSUE THREAD

**Issue by yktoo** [yktoo/indicator-sound-switcher#88]
Follow-up on #87.

Symbolic icons [should](https://jonbrettdev.wordpress.com/2013/08/24/gtk-symbolic-icon-woes/) use `#bebebeff` to be coloured properly in various themes.

**Comment by yktoo** [comment]
Resolved in 2.3.4.

**Comment by Ropid** [comment]
This `#bebebe` color doesn't seem to work in XFCE. I see a black icon all the time, no matter if I use a theme with light or dark panel.
