### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by token47** [yktoo/indicator-sound-switcher#89]
Thank you very much for developing this app. It's just about the right size. Simple, effective and intuitive.

I initially thought that it should be a gnome extension, but I had no problem adding it to startup applications and it just works, so I guess that is not strictly necessary.

I already tried about every sound chooser extension in existence and all have some kind of problem, I just find it amazing that it would be so difficult to make something that works nicely.

Thank you, from a happy user!

**Comment by yktoo** [comment]
You're very welcome!
