### ISSUE TITLE
Keystroke combination to open Sound Switcher list

### ISSUE THREAD

**Issue by dln949** [yktoo/indicator-sound-switcher#95]
Often I need to remotely access another computer.  When I do that, it works best to display the remote computer's desktop on my local client computer (Ubuntu 18.04.5, gnome shell 3.28.4) in full screen mode.  When I do that, the top panel is covered up, and I do not have access to the Sound Switcher icon in the system status area.  I have to first minimize the remote desktop display, then the top panel is revealed.  

Is there a keystroke combination I can use that will open the Sound Switcher list so I don't need to access the icon in the top panel?

**Comment by leobasilio** [comment]
Even if there were a keyboard shortcut, I believe your remote desktop client would forward it to the other computer, so it wouldn't work as intended.

**Comment by dln949** [comment]
Sorry, I meant that I would use such a keyboard shortcut when the focus is on another monitor that is not involved in the remote desktop session.  I failed to make that clear.

**Comment by yktoo** [comment]
There's no key specific for the Sound Switcher Indicator as the menu is controlled by the desktop manager.

For [Gnome Shell](https://help.gnome.org/users/gnome-help//stable/shell-keyboard-shortcuts.html.en), for instance, you can press <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Tab</kbd> to first select the top bar:
![topbar](https://user-images.githubusercontent.com/1675911/97671602-d7016780-1a88-11eb-8276-cdbc038e050f.png)

And then use the arrow keys to highlight the SSI icon and finally <kbd>Enter</kbd> to open the menu.
