### ISSUE TITLE
[BUG] missing dependency on Ubuntu 20.04

### ISSUE THREAD

**Issue by matemat13** [yktoo/indicator-sound-switcher#98]
**Describe the bug**
The sound switcher will crash with the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/indicator-sound-switcher", line 32, in <module>
    from indicator_sound_switcher.indicator import SoundSwitcherIndicator, APP_ID
  File "/usr/local/lib/python3.8/dist-packages/indicator_sound_switcher/indicator.py", line 21, in <module>
    from .config import Config, KeyboardManager
  File "/usr/local/lib/python3.8/dist-packages/indicator_sound_switcher/config.py", line 8, in <module>
    gi.require_version('Keybinder', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Keybinder not available
```
after a clean install using `sudo python3 setup.py install` on Ubuntu 20.04. Running `sudo apt install gir1.2-keybinder-3.0` fixes this problem. It seems that this dependency is missing in the install script.

**To Reproduce**
1. Get a clean installation of Ubuntu 20.04.
2. Clone the `indicator-sound-switcher` and checkout the latest release (`2.3.4`).
3. Install `indicator-sound-switcher` from source using the command `sudo python3 setup.py install` as per the instructions in the installation part of the documentation.
4. Run `indicator-sound-switcher` from the terminal.

**Expected behavior**
The `indicator-sound-switcher` will successfully run.

**Desktop (please complete the following information):**
 - **OS:** Ubuntu 20.04.
 - **Desktop environment:** i3wm 4.18
 - **Sound Switcher Indicator version:** 2.3.4

**Indicator log:**
Cannot fetch it since `indicator-sound-switcher` crashes after startup with the above error.

**Comment by yktoo** [comment]
Unfortunately, you don't seem to be able to install OS packages using `setup.py`, at least not with `distutils`. I will add the information to the Installation document that one has to install dependencies themselves prior to running `setup.py`.
